name: Deploy Angular to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular application
        run: ng build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: angular-app
          path: dist/allanlobodotcom

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: angular-app

      - name: Extract artifact
        run: tar -xzvf angular-app.tar.gz

      - name: Connect to Hostinger via SSH
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_ACCESS_TOKEN }}
          port: ${{ secrets.HOSTINGER_PORT }}
          command: "cd public_html/my-app && rm -rf * && cp -r ../angular-app/* ."

      - name: Restart Apache
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_ACCESS_TOKEN }}
          port: ${{ secrets.HOSTINGER_PORT }}
          command: "service apache2 restart"
